sonar.projectKey=Markst0105_flutter_petshop_dashboard
sonar.organization=testanalysissoftwaremanagement

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=flutter_petshop_dashboard
#sonar.projectVersion=1.0

# Source code and test paths
sonar.sources=lib
sonar.tests=test,integration_test

# Coverage report path
sonar.dart.coverage.reportPaths=coverage/lcov.info
sonar.coverageReportPaths=coverage/lcov.info

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
