name: Build
on:  
  push:    
    branches:      
      - '**'  
  pull_request:    
    types: [closed]

jobs:  
  sonarqube:    
    name: SonarQube    
    runs-on: windows-latest    
    steps:      
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1        
        with:          
          fetch-depth: 0  
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies and Build
        run: |
          flutter pub get
          flutter build web

      - name: Run Tests with Coverage
        run: |
          flutter test --coverage

      - name: Fix Coverage Report
        run: |
          dart run coverage:format_coverage --lcov --in=coverage/lcov.info --out=coverage/lcov.info --report-on=lib

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.coverageReportPaths=coverage/lcov.info
            -Dsonar.flutter.tests.reportPath=tests.output
